const { ethers } = require("hardhat");
const { POOL_ADDRESS } = require("./config");

async function main() {
    // Simulate the Oracle reporting rewards
    const Pool = await ethers.getContractAt("StakingPool", POOL_ADDRESS);
    
    // Simulate 0.05 ETH reward generated by validators
    const rewards = ethers.utils.parseEther("0.05");

    console.log("Oracle: Reporting Rewards...");
    const tx = await Pool.reportRewards(rewards);
    
    await tx.wait();
    console.log("Rewards Reported. All lsETH holders are now richer!");
}

main();
